---
new_page_extension: html
auto_deploy: true
admin_path: D:\TEMP\forestry
webhook_url: 
sections: 
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: 0.42.1
